[[ADIB]]
### LDAP Connection

Some issues connecting with LDAP via some ips, found that: ` 10.195.254.6:389 `  seems to work. 
Do some corrections on the filters and DN for PRD environments: 
```yml
ldap.java.naming.factory.initial: com.sun.jndi.ldap.LdapCtxFactory

ldap.com.sun.jndi.ldap.read.timeout: 3000

ldap.java.naming.provider.url: ldap://10.195.254.6:389,ldap://10.195.254.7:389

ldap.java.naming.security.principal: CN=srv-kafkaprd,OU=Service Accounts,DC=ADIB,DC=CO,DC=AE

ldap.java.naming.security.credentials:

ldap.java.naming.security.authentication: simple

ldap.user.search.scope: 2

ldap.java.naming.referral: follow

ldap.user.search.base: DC=DEVDC,DC=ADIB,DC=Local

ldap.group.search.base: OU=KAFKA,DC=DEVDC,DC=ADIB,DC=Local

ldap.user.name.attribute: sAMAccountName

ldap.group.name.attribute: cn

ldap.group.member.attribute.pattern: CN=(.*),OU=ADIB,OU=User Accounts,DC=DEVDC,DC=ADIB,DC=Local

ldap.user.object.class: user
```

### RBAC

RBAC Enabled, and extra LDAP Users configured. 
````yml
mds_super_user: srv-kafkaprd

mds_super_user_password: password

#

kafka_broker_ldap_user: srv-kafkaprd

kafka_broker_ldap_password:

#

schema_registry_ldap_user: srv-kafkaprd

schema_registry_ldap_password:

#

kafka_connect_ldap_user: srv-kafkaprd

kafka_connect_ldap_password:

#

ksql_ldap_user: srv-kafkaprd

ksql_ldap_password:

#

kafka_rest_ldap_user: srv-kafkaprd

kafka_rest_ldap_password:

#

control_center_ldap_user: srv-kafkaprd

control_center_ldap_password:
````
*I think `mds-super_user`  is the only one really needed since we will communicate through mTLS, so the principal will be extracted from the CN of the certificate*

With this config we got this error:

````text
ASK [confluent.kafka_broker : Grant role System Admin to Additional Kafka Broker System Admins] ************************************************************
Thursday 03 February 2022 21:47:08 +0400 (0:00:01.273) 0:04:23.839 *****
failed: [lpp2azapkfb1.adib.co.ae] (item=srv-kafkaprd) => {"ansible_loop_var": "item", "changed": false, "content": "", "elapsed": 30, "item": "srv-kafkaprd", "msg": "Status code was -1 and not [204]: Connection failure: ('The read operation timed out',)", "redirected": false, "status": -1, "url": "https://lpp2azapkfb1.adib.co.ae:8090/security/1.0/principals/User:srv-kafkaprd/roles/SystemAdmin"}
failed: [lpp1apkfb2.adib.co.ae] (item=srv-kafkaprd) => {"ansible_loop_var": "item", "changed": false, "content": "", "elapsed": 30, "item": "srv-kafkaprd", "msg": "Status code was -1 and not [204]: Connection failure: ('The read operation timed out',)", "redirected": false, "status": -1, "url": "https://lpp2azapkfb1.adib.co.ae:8090/security/1.0/principals/User:srv-kafkaprd/roles/SystemAdmin"}
failed: [lpp2azapkfb2.adib.co.ae] (item=srv-kafkaprd) => {"ansible_loop_var": "item", "changed": false, "content": "", "elapsed": 30, "item": "srv-kafkaprd", "msg": "Status code was -1 and not [204]: Connection failure: ('The read operation timed out',)", "redirected": false, "status": -1, "url": "https://lpp2azapkfb1.adib.co.ae:8090/security/1.0/principals/User:srv-kafkaprd/roles/SystemAdmin"}
failed: [lpp1azapkfb2.adib.co.ae] (item=srv-kafkaprd) => {"ansible_loop_var": "item", "changed": false, "content": "", "elapsed": 30, "item": "srv-kafkaprd", "msg": "Status code was -1 and not [204]: Connection failure: ('The read operation timed out',)", "redirected": false, "status": -1, "url": "https://lpp2azapkfb1.adib.co.ae:8090/security/1.0/principals/User:srv-kafkaprd/roles/SystemAdmin"}
failed: [lpp1azapkfb1.adib.co.ae] (item=srv-kafkaprd) => {"ansible_loop_var": "item", "changed": false, "content": "", "elapsed": 30, "item": "srv-kafkaprd", "msg": "Status code was -1 and not [204]: Connection failure: ('The read operation timed out',)", "redirected": false, "status": -1, "url": "https://lpp2azapkfb1.adib.co.ae:8090/security/1.0/principals/User:srv-kafkaprd/roles/SystemAdmin"}
failed: [lpp1apkfb1.adib.co.ae] (item=srv-kafkaprd) => {"ansible_loop_var": "item", "changed": false, "content": "", "elapsed": 30, "item": "srv-kafkaprd", "msg": "Status code was -1 and not [204]: Connection failure: ('The read operation timed out',)", "redirected": false, "status": -1, "url": "https://lpp2azapkfb1.adib.co.ae:8090/security/1.0/principals/User:srv-kafkaprd/roles/SystemAdmin"}
````

We solved with this config:

````yml
super.users: User:kafkaprd;User:dev-kafka.devdc.adib.local
````

But the problem comes again when trying to deploy Schema Registry:
````
2022-02-03 18:57:16,014] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Discovered group coordinator lpp1azapkfb1.adib.co.ae:9092 (id: 2147483647 rack: null) (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[2022-02-03 18:57:16,014] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Group coordinator lpp1azapkfb1.adib.co.ae:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable.isDisconnected: false. Rediscovery will be attempted. (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[2022-02-03 18:57:16,118] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Discovered group coordinator lpp1azapkfb1.adib.co.ae:9092 (id: 2147483647 rack: null) (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[2022-02-03 18:57:21,870] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Attempt to heartbeat failed since coordinator lpp1azapkfb1.adib.co.ae:9092 (id: 2147483647 rack: null) is either not started or not valid (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[2022-02-03 18:57:21,870] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Group coordinator lpp1azapkfb1.adib.co.ae:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: error response NOT_COORDINATOR.isDisconnected: false. Rediscovery will be attempted. (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[2022-02-03 18:57:23,815] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Discovered group coordinator lpp2azapkfb2.adib.co.ae:9092 (id: 2147483644 rack: null) (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[2022-02-03 18:57:23,913] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Attempt to heartbeat failed since coordinator lpp2azapkfb2.adib.co.ae:9092 (id: 2147483644 rack: null) is either not started or not valid (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[2022-02-03 18:57:23,914] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Group coordinator lpp2azapkfb2.adib.co.ae:9092 (id: 2147483644 rack: null) is unavailable or invalid due to cause: error response NOT_COORDINATOR.isDisconnected: false. Rediscovery will be attempted. (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
````

The seems to be with the authorization in MDS, we try to solve with the `ssl.principal.mapping.rules` with weird behaviour, sometimes seems to works and not another.
